### ISSUE TITLE
Scroll position in callback reports 0

### ISSUE THREAD

**Issue by travisrobie** [KingSora/KingSora.github.io#2]
If you check the scroll position in the 'complete' callback, it reports 0.
If you check after another 50ms it will report the correct position.

See https://codepen.io/anon/pen/YROYmX?editors=1010

Thanks for creating this awesome plugin!

Best,
Travis

**Comment by KingSora** [comment]
Good day!

You have accidentaly opened this issue on the incorrect repository. This repository is only responsible for the documentation page. The correct repository would be [here](https://github.com/KingSora/OverlayScrollbars).

I've looked into your issue and this is happening because of your very low scroll-duration which is just `1ms` in your example.

The coordinates & scroll-infos gets updated if the `scroll`-event of the `viewport`-element fires. 
Unfortunately there seems to be a bit of a native delay before a scroll event gets fired, so the actual scroll events gets fired **after** the complete callback. To demonstrate / prove this I've created a small [demo](https://jsfiddle.net/3dnLh95y/).

In case you need a workaround until it's fixed, I've created a [example](https://jsfiddle.net/3dnLh95y/1/) for you.

Thank you for the bug report, I'll fix this in the next version of the plugin which will be released pretty soon.

**Comment by travisrobie** [comment]
Oops! Sorry for putting this in the wrong repo.. haven't filed a report before!
Thank you for the workaround.. I really appreciate it!

Travis

**Comment by KingSora** [comment]
It should be fixed now in [v1.6.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.6.0).
Thanks again for your report!

**Comment by travisrobie** [comment]
Cool will try it out!

Best,
Travis
